### ISSUE TITLE
Segmentation Fault on x86_64 when running from dev branch

### ISSUE THREAD

**Issue by mikenye** [Mictronics/readsb-protobuf#13]
Hi @Mictronics,

I understand that the dev branch is just that, dev... So if this is a known issue then no problems - I just wanted to make you aware.

Just an FYI - when building/running the current dev version (4.0.2) I've had multiple users (myself included) report segmentation faults.

Issue: https://github.com/mikenye/docker-readsb-protobuf/issues/15

If you need any additional information, I can pretty easily reproduce the issue.

Cheers.

**Comment by Mictronics** [comment]
@mikenye Can you provide the command line that the service is starting with?

Since when the problem occurs? Can you narrow down if it's related to commits from last days?

**Comment by Mictronics** [comment]
@mikenye Never mind. Fixed.

**Comment by mikenye** [comment]
Thanks @Mictronics, really appreciate you fixing this so quickly.
