### ISSUE TITLE
Error message "InvalidStateError: A mutation operation was attempted on a database that did not allow mutations." on readsb webinterface

### ISSUE THREAD

**Issue by BugDeliverer** [Mictronics/readsb-protobuf#15]
Setup: Docker container readsb-protobuf running on headless Arch Linux. Container is checked daily and updated if necessary.
About 2 weeks ago everything was fine. Today accessing the readsb webinterface (default port :8080) leads to the message
"InvalidStateError: A mutation operation was attempted on a database that did not allow mutations."
Afterwards the map loads as usual, but no planes are listed or shown.

**Comment by Mictronics** [comment]
Clear the application (webinterface) cache in browser, also delete the indexedDB storage. In Chrome that's via F12 developer tools, the Application. (while webinterface is open)
The indexedDB will be initialized when you reload the page. Developer console has some logging for that.

**Comment by BugDeliverer** [comment]
The error occurred when connecting with a clean installed laptop.
A few days later (using another laptop) everything is fine again.
