### ISSUE TITLE
Web Mapping

### ISSUE THREAD

**Issue by howellx** [Mictronics/readsb-protobuf#25]
This is more of a question than an issue, but I'm wondering if this repo has the feature of displaying the aircrafts onto a global map. I notice there is a webapp folder, but I can't seem to understand if the mapping is accessible and if it is, how to do so. Thanks, any help would be appreciated.

**Comment by Mictronics** [comment]
The web application (global map) is served by the lighttpd web server (one of the dependencies). See INSTALL.md for build instructions. Easiest is to build the Debian package and then install that package.

If you want a careless installation look here: [https://github.com/adsbfi/adsb-fi-scripts](https://github.com/adsbfi/adsb-fi-scripts)
It's based on readsb.

**Comment by howellx** [comment]
Ok thank you, would I just open my server ip address in my browser after installing and running to access the map

**Comment by Mictronics** [comment]
Yes.

**Comment by howellx** [comment]
I'm still having issues. When I put my server's ip address into the browser just says the "This site can't be reached". When I put in port 8080, it is able to connect and opens up what looks like to be flightaware's map GUI, but the main panel where the map should be is just all white and none of the buttons on the GUI work. Am I doing something wrong?

**Comment by Mictronics** [comment]
The map is accessible via http://[your_server_ip]/radar
The statistics via http://[your_server_ip]/graphs

**Comment by howellx** [comment]
Sorry for the late reply, got caught up with other things. The web mapping isn't working. Is there a certain option I need to run the program with? I've been running it with "--net" which hasn't been working.

**Comment by Mictronics** [comment]
RECEIVER_OPTIONS="--device 0 --device-type rtlsdr --gain -10 --ppm 0"
DECODER_OPTIONS="--max-range 360"
NET_OPTIONS="--net --net-heartbeat 60 --net-ro-size 1200 --net-ro-interval 0.1 --net-ri-port 0 --net-ro-port 30002 --net-sbs-port 30003 --net-bi-port 30004,30104 --net-bo-port 30005"
OUTPUT_OPTIONS="--rx-location-accuracy 2"

These are the options readsb runs with by default as a service.

**Comment by howellx** [comment]
So the web mapping should be enabled by default?
