### ISSUE TITLE
Can you send me WMM2020LegacyC.zip file of NOAA?

### ISSUE THREAD

**Issue by Armando123x** [Mictronics/readsb-protobuf#26]
Hello, I need this program in C because it don't exist more in NOAA page. Please, my email contact is armando.castro.c@uni.pe

**Comment by Mictronics** [comment]
1) Open https://www.ncei.noaa.gov/products/world-magnetic-model
2) Click the tab `Third-Party Software` to unfold
3) Click the download link

https://www.ngdc.noaa.gov/geomag/WMM/data/WMM2020/WMM2020LegacyC.zip
