### ISSUE TITLE
Corona RP8D1

### ISSUE THREAD

**Issue by wimalopaan** [Mictronics/readsb-protobuf#30]
Sorry for opening this issue, but I want to contact you because of yout rev-eng of the RP8D1 receiver. I was unable to get yout email / contact in the first place.

**Comment by Mictronics** [comment]
Email is not hidden. e.g. [https://github.com/Mictronics/readsb-protobuf/blob/dev/debian/changelog](https://github.com/Mictronics/readsb-protobuf/blob/dev/debian/changelog)
