### ISSUE TITLE
dh-systemd

### ISSUE THREAD

**Issue by samlander** [Mictronics/readsb-protobuf#32]
When I got the prerequisites, dh-systemd was not available (debian 12.5, Bookworm, Linux 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux)

I looked up dh-systemd over here https://packages.debian.org/buster/dh-systemd

Package: dh-systemd (12.1.1)
debhelper add-on to handle systemd unit files - transitional package
This package is for transitional purposes and can be removed safely.

I feel that I have probably "transitioned", and that I could safely remove it (from the readsb build).... 
I did, and the result was that it everything built and installed and ran correctly

I don't know if it helps, but apt said, and still says, these things for me:
```
$ apt list dh-sys*
Listing... Done
dh-sysuser/stable 1.3.9+really1.4.3 all
$ apt list debhelp*
Listing... Done
debhelper/stable,now 13.11.4 all [installed]
```

**Comment by jensenpat** [comment]
@samlander I was able to reproduce this on Debian arm64. I successfully removed dh-systemd from the unit file and was able to build, install the package and run correctly.
