### ISSUE TITLE
Error sem_timedwait ETIMEDOUT in readsbrrd.c

### ISSUE THREAD

**Issue by dervomsee** [Mictronics/readsb-protobuf#5]
Hi,
i get often messeges like this in my journald:
readsbrrd[4259]: /var/lib/collectd/rrd/localhost/readsb/aircraft_gps.rrd: illegal attempt to update using time 1596799197 when last update time is 1596799197 (minimum one second step)
I the issue is, that sem_timedwait in readsbrrd.c, line 582 returns with errno ETIMEDOUT
https://github.com/Mictronics/readsb-protobuf/blob/4318b218a193255b0e0d1d0f9c179f196be7ec3c/readsbrrd.c#L582

**Comment by Mictronics** [comment]
Restart the readsbrrd service while readsb is running:
`sudo service readsbrrd restart`

**Comment by dervomsee** [comment]
Hi,
i modified the line, where sem_timedwait is called to the following, to the the return value:
```c
        // Wait for new statistic from readsb process, or read anyway on timeout.
        int tmp = sem_timedwait(stats_semptr, &ts);
        if(tmp!=0)
            fprintf(stderr, "error sem_timedwait: %s\n", strerror(errno));
        else
            fprintf(stderr, "no error sem_timedwait: %d\n", tmp);
```

After a restart of the service, the error output is as follows:
https://gist.github.com/dervomsee/d6e70884db0f6a18a42ea7bd46d36bb8

**Comment by Mictronics** [comment]
@dervomsee Please test the latest commit that should fix the issue.

**Comment by dervomsee** [comment]
@Mictronics ~This solves the issue. Thanks!~

**Comment by dervomsee** [comment]
Too early. The issue still exists. It was solved until i rebooted the system.
But the fprintf in line 590 is not getting called. https://github.com/Mictronics/readsb-protobuf/blob/8494b76217da1f2b2ff180145129de8e18c81a97/readsbrrd.c#L590 
Do you have any debugging code in mind that i can run on my Pi?

**Comment by Mictronics** [comment]
What error you see in journal?

**Comment by dervomsee** [comment]
Here is a log file ( journalctl -r -u readsbrrd -b > log10082020.txt ):
[log10082020.txt](https://github.com/Mictronics/readsb-protobuf/files/5051504/log10082020.txt)

**Comment by Mictronics** [comment]
Does this problem occur only after reboot?
What happens when you restart either readsb or readsbrrd service after reboot?

I know of a sporadic race condition after reboot which is caused by service start through systemd.

**Comment by dervomsee** [comment]
No, it happens also when restarting the sysd unit (see line 43997):
[log10082020_restart.txt](https://github.com/Mictronics/readsb-protobuf/files/5051707/log10082020_restart.txt)

**Comment by Mictronics** [comment]
I can not reproduce. Neither with reboot nor restarting readsb and readsbrrd services in random order.
You may put some test output below `r = sem_timedwait(stats_semptr, &ts);`.
Compile and stop the readsbrrd service. Run `readsbrrd --rrd-step 60 --rrd-dir /var/lib/collectd/rrd/localhost/readsb` in build folder and check if that test output appears continuously or in 60 second interval.

From your logs it seems the rrd update functions are called frequently within the same timestamp second, hence the error message.

Last solution would be storing of the last update timestamp and return on update if the actual and last are equal.

**Comment by dervomsee** [comment]
I found a workaround for the problem. I added the following line to the readsb.service file `ExecStartPre=/bin/sleep 60`. This delays the readsb startup. 
After restarting my Pi the time is reset to 2020-04-01 19:24:08. After getting a IP ntpd fetches the time and it will be set to the current time. Without the additional line readsb.service gets started before correcting the time.
Could this four month time change be a problem?

**Comment by Mictronics** [comment]
Yes that's the problem. The timestamp is stored in RRD files according to system time. When your system time is in the past, compared to what is stored in the last RRD entry, then you will get the error.
But this is nothing readsb can solve. I will put a note in README for that.

This delay should be in readsbrrd.service file. Only the RRD collector is affected, not the decoder.

**Comment by Mictronics** [comment]
What I can do in case where system time is in the past: Read the last entry timestamp from RRD file and output a more meaningful error message instead of updating the file.

**Comment by Mictronics** [comment]
`Aug 11 15:24:07 adsbreceiver readsbrrd[16018]: error system time in past compared to last entry in dbfs_noise.rrd.`
Better error message I hope.

**Comment by dervomsee** [comment]
Your better error message appears in the log, but it creates very fast huge log files. This 12MB logfile is created in ~4minutes. Would it be better to stop readsbrrd with an error message?
[log12082020_restart.txt](https://github.com/Mictronics/readsb-protobuf/files/5061667/log12082020_restart.txt)

The delayed startup is also a bit more complex. Delaying readsbrrd.service is not enough, readsb.service needs to be delayed.
Also the sleep function often gets killed with the following message: `Process: 1279 ExecStartPre=/bin/sleep 90 (code=killed, signal=TERM)`
When changing the unit type from `Type=simple` to `Type=oneshot` it work on every tested reboot. The unit file would be the following:

```
# readsb service for systemd

[Unit]
Description=readsb ADS-B receiver
Documentation=https://github.com/mictronics/readsb
Wants=network.target
After=network.target

[Service]
EnvironmentFile=/etc/default/readsb
User=readsb
RuntimeDirectory=readsb
RuntimeDirectoryMode=0755
ExecStartPre=/bin/sleep 90
ExecStart=/usr/bin/readsb \
 $RECEIVER_OPTIONS $DECODER_OPTIONS $NET_OPTIONS $OUTPUT_OPTIONS \
 --write-output /run/readsb --quiet
Type=oneshot
Restart=on-failure
RestartSec=30
Nice=-5

[Install]
WantedBy=default.target
```

**Comment by dervomsee** [comment]
And by adding a additional option `DELAY_OPTION=90` in the `/etc/default/readsb` file, the delay is optional:
```
# readsb service for systemd

[Unit]
Description=readsb ADS-B receiver
Documentation=https://github.com/mictronics/readsb
Wants=network.target
After=network.target

[Service]
EnvironmentFile=/etc/default/readsb
User=readsb
RuntimeDirectory=readsb
RuntimeDirectoryMode=0755
ExecStartPre=/bin/sleep $DELAY_OPTION
ExecStart=/usr/bin/readsb \
 $RECEIVER_OPTIONS $DECODER_OPTIONS $NET_OPTIONS $OUTPUT_OPTIONS \
 --write-output /run/readsb --quiet
Type=simple
Restart=on-failure
RestartSec=30
Nice=-5

[Install]
WantedBy=default.target
```

**Comment by Mictronics** [comment]
Again, it's not the purpose of readsbrrd to solve problems with system time. And I see no reason to delay my tools because of problems elsewhere. On a Pi, fake hwclock will provide an instant reasonable system time after reboot until it gets updated from online or other sources. It seems in your case fake hwclock is either not installed or gets no update via cron job.

Btw, in case you have any other RRD collection running via collectd then you should have the same problem there.

Stopping readsbrrd on failure will cause a service restart every 30s with current configuration. Here again I seen no reason to do this.
What we can do is silently skipping updates in case of errors with system time. But then one will notice problems only because of missing graph updates, and without any error message, will have no glue what's going on. This causes more questions than answers.

**Comment by Mictronics** [comment]
For service startup delay you may have a look at https://wiki.archlinux.org/index.php/Systemd/Timers

**Comment by dervomsee** [comment]
Yes, this is also proposed here: https://stackoverflow.com/a/52592734
